# Generated by Django 5.0.1 on 2024-01-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='apellidos')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('celular', models.CharField(max_length=9, verbose_name='Numero de Celular')),
                ('fecha_inicio', models.DateField(auto_now=True, verbose_name='Fecha de Inscripción')),
                ('fecha_final', models.DateField()),
                ('mensualidad', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pago de mensualidad')),
            ],
        ),
    ]
