# Generated by Django 5.0.1 on 2024-01-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesFrecuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='nombres')),
                ('celular', models.CharField(max_length=9, verbose_name='Numero de Celular')),
                ('fecha_ingresada', models.DateTimeField(auto_now=True, verbose_name='Fecha de Inscripción')),
                ('pago', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pago')),
            ],
        ),
    ]
