# Generated by Django 5.0.1 on 2024-01-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientesfrecuentes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ('id',), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='clientesfrecuentes',
            options={'ordering': ('id',), 'verbose_name': 'Cliente Frecuente', 'verbose_name_plural': 'Clientes Frecuentes'},
        ),
    ]
