# Generated by Django 5.0.1 on 2024-01-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='apellidos')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('celular', models.CharField(max_length=9, verbose_name='Numero de Celular')),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], max_length=50, verbose_name='Turno')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pago de sueldo')),
            ],
        ),
    ]
