# Generated by Django 5.0.1 on 2024-01-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleados_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Pago de sueldo'),
        ),
    ]
