# Generated by Django 5.0.1 on 2024-01-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.AddField(
            model_name='productos',
            name='tipo_producto',
            field=models.CharField(choices=[('P', 'Proteina'), ('V', 'Vitaminas')], default='', max_length=1, verbose_name='Tipo de Producto'),
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
