# Generated by Django 5.0.1 on 2024-01-17 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_productos_categoria_productos_tipo_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(max_length=30, verbose_name='Tipo de Producto')),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Productos',
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='productos',
            name='tipo_producto',
        ),
        migrations.AddField(
            model_name='productos',
            name='tipo_productos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='productos.tipoproducto'),
        ),
    ]
