# Generated by Django 5.0.1 on 2024-01-30 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_tipoproducto_remove_productos_tipo_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='tipo_productos',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.tipoproducto'),
        ),
    ]
